package memento;

public interface Memento {
//MARKER!
//LA INSERISCO IN MODO TALE CHE NELLE CLASSI DOVE NECESSITO DI UN MEMENTO POSSA IMPLEMENTARE QUESTA INTERFACCIA FACENDO
//CAPIRE CHE SI TRATTA DI UN OGGETTO CAPACE DI INCAPSULARE UNO STATO PER RIPRISTINARLO.
//IN QUESTO CASO IO AVRO' UNA SOLA IMPLEMENTAZIONE CONTENUTA NEL PANNELLODISEGNO CHE USERO' PER IL CARICAMENTO DI UN
//ORGNIGRAMMA DA FILE E PER DISEGNARLO DOPO AVER ELIMINATO LA RADICE. IN QUESTO MODO QUELLA CLASSE SARA VISIBILE SOLO AL PANNELLO
//CHE SI CONFIGURA COME ORIGINATOR (AVREI POTUTO CREARE INTERFACCIA CON METODI GETMEMENTO E SETMEMENTO DA FARGLI IMPLEMENTARE),
//RENDENDOLA INVISIBILE ALL'ESTERNO E GARANTENDO CHE UNA VOLTA RICEVUTO UN MEMENTO VERIFICHI CON UN CAST SE L'ORIGINATOR È LUI
//(IN QUESTO CASO ABBIAMO SOLO QUESTO MEMENTO QUINDI È SCONTATO, MA IN CONTESTI PIU' COMPLICATI NON POTREBBE ESSERE SCONTATO)
//I CARETAKER D'ALTRO CANTO SI LIMITERANNOAD UTILIZZARE UN OGGETTO DI TIPO MEMENTO.


}
